/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'masa' at '16/11/21 7:56' with Gradle 3.2
 *
 * @author masa, @date 16/11/21 7:56
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
