---
language: java
sudo: false

branches:
  only: 
    - master
    - thrift

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.jdk

env:
  global:
    - GRADLE_OPTS=-Xmx256m

matrix:
  include:
  - os: linux
    env: JAVA_HOME=$HOME/.jdk/default PATH=$JAVA_HOME/bin:$PATH
  - os: osx

install:
  - true

addons:
  apt:
    packages:
      - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .travis/install-jdk.sh ; fi
  - .travis/clean-m2-repo.sh
  - cmake --version
  - java -version
  - ./gradlew --version

script:
  - if [[ "$TRAVIS_BRANCH" == "thrift" ]]; then ./thrift/build/docker/scripts/cmake.sh   ; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew --no-daemon --stacktrace build ; fi
